stages:
  - build
  - test
  - deploy
  

maven-build:
  stage: build
  script: 
    - mvn package
  artifacts:
     paths:
       - target/*.war 



include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


# dploy:
#   stage: deploy
#   script:
#     - cp /home/gitlab-runner/builds/p6GwWc_M/0/Fineshift2023/Train-Ticket-Reservation-System/target/TrainBook-1.0.0-SNAPSHOT.war /opt/tomcat/webapps


