stages:
  - build
  - test
  - deploy
  

maven-build:
  stage: build
  tags:
    - ramdas
  script: 
    - mvn clean package
    - pwd
  artifacts:
     paths:
       - target/*.war 



include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


dploy:
  stage: deploy
  tags:
    - ramdas
  script:
    -  cp  /home/gitlab-runner/builds/jB45YxjdX/0/Fineshift2023/Regstration_form/target/*.war /opt/tomcat/webapps


