stages:
  - build
  # - test
  # - deploy
  

maven-build:
  stage: build
  tags:
    - shell
  script: 
    - mvn clean package
    - pwd
  artifacts:
     paths:
       - target/*.war 



# include:
#   - template: Jobs/SAST.gitlab-ci.yml
#   - template: Security/Secret-Detection.gitlab-ci.yml


dploy:
  stage: deploy
  tags:
    - shell
  script:
    -  cp  /home/fs-swapnil/builds/xdLbaBMfL/0/fineshift/users/swapnil/Regstration_form/target/*.war /opt/tomcat/webapps


