stages:
  - build
  - deploy
  
maven-build:
  stage: build
  tags:
    - shell
  script: 
    - mvn clean package
    - pwd
  artifacts:
     paths:
       - target/*.war 

deploy:
  stage: deploy
  tags:
    - shell
  script:
    -  cp  /home/fs-swapnil/builds/xdLbaBMfL/0/fineshift/users/swapnil/Regstration_form/target/*.war /opt/tomcat/webapps


