# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

stages:
- stage:
  pool:
    Sonar
  jobs:
  - job: MavenBuild
    steps:
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'snyk'
        testType: 'app'
        monitorWhen: 'always'
        failOnIssues: true
    
    
    #- task: SonarQubePublish@5
     # inputs:
      #  pollingTimeoutSec: '300'

    - task: CopyPublishBuildArtifacts@1
      inputs:
        CopyRoot: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.war'
        ArtifactName: 'artifact'
        ArtifactType: 'Container'
    # - task: CopyFiles@2
    #   displayName: 'Copy Files to artifact staging directory'
    #   inputs:
    #       SourceFolder: '$(System.DefaultWorkingDirectory)'
    #       Contents: '**/target/*.war'
    #       TargetFolder: $(Build.ArtifactStagingDirectory)
    
    # - upload: $(Build.ArtifactStagingDirectory)
    #   artifact: artifact
   # - task: SnykSecurityScan@1
   #   inputs:
   #     serviceConnectionEndpoint: 'Snyk'
    #    testType: 'app'
      #  monitorWhen: 'always'
    #    failOnIssues: false
      #  projectName: 'employee_registration'
    
#- stage:
 # pool:
 #   Sonar
  #jobs:
  #- job: Deploy
    #steps:
    #- script:
      #  echo $(Build.ArtifactStagingDirectory)